### ISSUE TITLE
Remove warning default tagline

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#19]
Yoast SEO 2.3 introduced
> ... a warning advising to change the tagline, if a site still has the default WordPress tagline "just another WordPress site".

that needs to go

**Comment by robneu** [comment]
I was actually wondering about this too. I've worked on some sites that opted for that plugin rather than the one built into Yoast because they're huge and Yoast struggled to keep up.

Personally I've used the Sitemap in Yoast the majority of the time, mainly because it allows for full control over indexation in one place IE noindex and remove from the sitemap simultaneously.

**Comment by senlin** [comment]
@robneu this comment is for issue #21 :)

**Comment by robneu** [comment]
@senlin Haha yeah, sorry about that. Too many tabs open. :grin:

**Comment by QWp6t** [comment]
I think ti's useful to keep it. This plugin is about aiding with SEO. It is definitely within the purview of a SEO plugin to let users know that the tagline should be changed.

Otherwise you can get this...
![Just another WordPress site](https://cloud.githubusercontent.com/assets/2104321/11674513/778220bc-9dd6-11e5-8360-a2de61e888f8.jpg)

**Comment by senlin** [comment]
@robneu 
> Do we want to get rid of all notices and the entire notice system or only specific notices?

My vote would go to remove the lot (the entire notice system). Most people actually do know what they're doing and notices are irritating at best. For the few that don't know, there will be some instructions available.

@QWp6t I think that the default WP tagline has nothing to do with SEO when a SEO plugin has been installed. The SEO plugin should have a setting what the homepage will show and that setting should not automatically default to the tagline.

I just have the feeling that Team Yoast assumes that their users are stupid and therefore irritate the userbase with notices. I would like to see the userbase of the YMBE SEO plugin as pretty conscious people and certainly not a stupid bunch. Therefore I really would like to get rid of all notices including the tagline notice.

**Comment by senlin** [comment]
reverted removal of "Reminder: Access to robots is currently being blocked." as we already changed the wording of this with issue #27 (previously it was called Huge SEO issue and had a red danger color, in issue 27 we changed it into an orange warning color and changed the wording too).
