### ISSUE TITLE
Sitemap in or out?

### ISSUE THREAD

**Issue by senlin** [senlin/ymbeseo#21]
What are we going to do with the sitemap functionality?

When we decide to remove the functionality entirely, we can recommend the [Google Sitemap Generator plugin](https://wordpress.org/plugins/google-sitemap-generator/) by Arne Brachold.

Input please on whether to keep the functionality or simply remove the bloat.

**Comment by robneu** [comment]
I was actually wondering about this too. I've worked on some sites that opted for that plugin rather than the one built into Yoast because they're huge and Yoast struggled to keep up.

Personally I've used the Sitemap in Yoast the majority of the time, mainly because it allows for full control over indexation in one place IE noindex and remove from the sitemap simultaneously.

**Comment by senlin** [comment]
I also mostly use the functionality that comes with Yoast.

I think it is important though to ask ourselves the following questions:

1. if Joost and team already struggled to keep up, then why would that be any different for us?
2. does a sitemap really belong to SEO?

I don't think it is a bad idea to advise people to use another plugin for the sitemap functionality

**Comment by robneu** [comment]
1. It probably will be an issue for us. It's always been an issue for WordPress SEO. Endpoints are tricky, performance issues, all kinds of stuff.

2. It definitely does belong to SEO. I wouldn't consider any site without a sitemap to be fully optimized.

I'm pretty torn here. On the one hand I really don't want to have to deal with the overhead caused by the code for sitemaps but I also feel like it's a pretty important and useful feature. Hopefully some more people have thoughts on the subject.

**Comment by senlin** [comment]
Could it be an idea to add it as a module or addon or something like that?

**Comment by robneu** [comment]
Splitting it out into a separate add-on plugin would probably make maintaining it and the core plugin a bit easier.

**Comment by senlin** [comment]
If we're going that route we "only" need to find someone who would be willing to maintain that addon...

**Comment by senlin** [comment]
As I have not received any emails from sitemap volunteers, I'm going to remove the lot from the plugin and add the recommendation to use Arne Brachold's [Google Sitemap Generator](https://wordpress.org/plugins/google-sitemap-generator/) instead.

**Comment by senlin** [comment]
Not sure whether these strings can be deleted, hopefully someone can have a look at those?
 * clear_sitemap_cache

* blocking_files

* clear_sitemap_cache (seems to be used by other function too?)
	related: clear_transient_cache
	related: register_cache_clear_option
	related: ymbeseo_invalidate_sitemap_cache

**Comment by lomars** [comment]
Sorry i come late, i was traveling a bit without network stuff…

Using Google Sitemap Generator instead is not a good solution for multilingual websites (for example if you use WPML plugin). A lot of people use Yoast sitemap functionality.

I was thinking that the purpose of this work was to keep the plugin as it was in version 2.3.5, without all the annoying "little things" as your plugin "SO Clean Up Yoast SEO" does, with a retro-compatibility for Yoast SEO ex users (database entries)…
So i am a bit disappointed now, looking at the evolution of this fork.

Regards

**Comment by senlin** [comment]
So are you volunteering to keep the sitemap functionality working and you are committing to this for at least two years?

The purpose of this fork is to remove the bloat from the original plugin. The sitemap functionality is not always working smoothly and it seems that team Yoast has had troubles with it in the past. 

After more than two weeks after my request for someone to step up, I really need to move on, so I removed the lot. If you're not happy about that, then you can fork the development branch, revert the commits that removed the sitemap and form a plan to make it an addon that can be used.

If you cannot do that, then it is also fine of course, then I can only apologise to you and tell you that it is impossible to please everyone :)

**Comment by lomars** [comment]
Hi senlin,
Sorry, I am not blaming you  :) . 
As i have tell you early by mail, i am not a lead developer as you are, and i am not used to Github. 
But i work on wordpress/woocommerce multilingual websites for clients and i have codeveloped a private plugin for wordpress/woocommerce.
So i don't know if i have the skills to make sitemap functionality an add-on, alone on my side. I need to think about it. I will tell you quickly.

By another side, I am in contact with the excellent author of the young plugin "The SEO Framework", a very clean alternative to Yoast SEO plugin (with nice improvements planned for 2016).

Regards

**Comment by Hube2** [comment]
I also don't want to give up most of the sitemap functionality that is offered by the original Yoast plugin. However, I think that in order to keep this plugin manageable for the limited number of people that are so far wiling to help maintain it, that it might be better to split out the sitemap into a separate plugin altogether.
